# Generated by Django 3.1.7 on 2021-04-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20210429_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(default='')),
                ('time', models.TimeField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
