# Generated by Django 3.1.7 on 2021-04-29 20:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20210429_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 20, 47, 47, 68747, tzinfo=utc)),
        ),
    ]
