# Generated by Django 3.1.7 on 2021-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20210429_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
